name: Promote Docker image to latest
on:
  workflow_dispatch:
jobs:
  dockerize_and_push:
    name: Tag latest and push to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag image
        run: docker tag ghcr.io/palladians/supso:$(git rev-parse --short HEAD) ghcr.io/palladians/supso:latest
      - name: Push to GHCR
        run: docker push ghcr.io/palladians/supso:latest
