name: Dockerize latest version
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  dockerize_and_push:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nixpacks
        run: |
          curl -LO https://github.com/railwayapp/nixpacks/releases/download/v1.21.1/nixpacks-v1.21.1-amd64.deb
          sudo dpkg -i nixpacks-v1.21.1-amd64.deb
      - name: Copy .env
        run: cp .env.example .env
      - name: Build image
        run: nixpacks build .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GHCR
        run: docker push ghcr.io/palladians/supso:$(docker images | awk '{print $1}' | awk 'NR==2')
